[workspace]
resolver = "2"
members = ["crates/cpm-core"]

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT"

[workspace.dependencies]
serde_json = "1"
sha2 = "0.10"
dunce = "1"
walkdir = "2"
tempfile = "3"
insta = "1"

[profile.release]
opt-level = "z"
lto = "thin"
strip = true
codegen-units = 16
